url = "https://www.booking.com"
months ={1:31,2:29,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
avaliable_currencies=[['Argentine Peso', 'ARS'],
 ['Australian Dollar', 'AUD'],
 ['Azerbaijani Manat', 'AZN'],
 ['Bahraini Dinar', 'BHD'],
 ['Brazilian Real', 'BRL'],
 ['Bulgarian Lev', 'BGN'],
 ['Canadian Dollar', 'CAD'],
 ['Chilean Peso', 'CLP'],
 ['Chinese Yuan', 'CNY'],
 ['Colombian Peso', 'COP'],
 ['Czech Koruna', 'CZK'],
 ['Danish Krone', 'DKK'],
 ['Egyptian Pound', 'EGP'],
 ['Euro', 'EUR'],
 ['Fijian Dollar', 'FJD'],
 ['Georgian Lari', 'GEL'],
 ['Hong Kong Dollar', 'HKD'],
 ['Hungarian Forint', 'HUF'],
 ['Indian Rupee', 'INR'],
 ['Indonesian Rupiah', 'IDR'],
 ['Israeli New Shekel', 'ILS'],
 ['Japanese Yen', 'JPY'],
 ['Jordanian Dinar', 'JOD'],
 ['Kazakhstani Tenge', 'KZT'],
 ['Kuwaiti Dinar', 'KWD'],
 ['Malaysian Ringgit', 'MYR'],
 ['Mexican Peso', 'MXN'],
 ['Moldovan Leu', 'MDL'],
 ['Namibian Dollar', 'NAD'],
 ['New Taiwan Dollar', 'TWD'],
 ['New Zealand Dollar', 'NZD'],
 ['Norwegian Krone', 'NOK'],
 ['Omani Rial', 'OMR'],
 ['Polish Złoty', 'PLN'],
 ['Pound Sterling', 'GBP'],
 ["Property's Currency", '€$£'],
 ['Qatari Riyal', 'QAR'],
 ['Romanian Leu', 'RON'],
 ['Russian Ruble', 'RUB'],
 ['Saudi Arabian Riyal', 'SAR'],
 ['Singaporean Dollar', 'SGD'],
 ['South African Rand', 'ZAR'],
 ['South Korean Won', 'KRW'],
 ['Swedish Krona', 'SEK'],
 ['Swiss Franc', 'CHF'],
 ['Thai Baht', 'THB'],
 ['Turkish Lira', 'TRY'],
 ['U.S. Dollar', 'USD'],
 ['Ukrainian Hryvnia', 'UAH'],
 ['United Arab Emirates Dirham', 'AED'],
 ['West African CFA Franc', 'XOF']]
 